[project]
name = "sp28337-bot"
version = "0.1.0"
description = "My first telegram bot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.21.0",
    "black>=25.9.0",
    "dotenv>=0.9.9",
    "email-validator>=2.3.0",
    "pydantic-settings>=2.10.1",
]
